{% set name = "uvloop" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3bf12b0fda68447806a7ad847bfa591613177275d35b6724b1ee573faa3704e3

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --config-settings=--global-option='build_ext' --config-settings=--global-option='--cython-always' --config-settings=--global-option='--use-system-libuv'
  skip: true  # [py<38 or win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython >=3.0,<4.dev0
    - pip
    - libuv 1.44.2
    - setuptools >=60
    - wheel
  run:
    - python
    - {{ pin_compatible("libuv", max_pin="x") }}

test:
  source_files:
    - pyproject.toml
    - tests
  imports:
    - uvloop
  requires:
    - pip
    - pytest
    - psutil
    - pyopenssl
  commands:
    - pip check
    - pytest -ra -k "not (test_sourcecode)" # [not (osx and arm64)]
    # skip test_process_delayed_stdio__not_paused__no_stdin: time is not monotonic on CI
    - pytest -ra -k "not (test_sourcecode or test_process_delayed_stdio__not_paused__no_stdin or test_create_ssl_server_manual_connection_lost)" # [osx and arm64]

about:
  home: https://github.com/MagicStack/uvloop
  license: MIT OR Apache-2.0
  license_family: Other
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
  summary: Ultra fast implementation of asyncio event loop on top of libuv.
  description: |
    uvloop is a fast, drop-in replacement of the built-in asyncio event loop.
    uvloop is implemented in Cython and uses libuv under the hood.
  doc_url: https://uvloop.readthedocs.io/
  dev_url: https://github.com/MagicStack/uvloop

extra:
  recipe-maintainers:
    - nehaljwani
    - carlodri
    - jakirkham
