{% set name = "uvloop" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0246f4fd1bf2bf702e06b0d45ee91677ee5c31242f39aab4ea6fe0c51aedd0fd

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --config-settings=--global-option='build_ext' --config-settings=--global-option='--cython-always' --config-settings=--global-option='--use-system-libuv'
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython >=0.29.36,<0.30.0
    - pip
    - libuv 1.44.2
    - setuptools
    - wheel
  run:
    - python
    - {{ pin_compatible("libuv", max_pin="x") }}

test:
  source_files:
    - pyproject.toml
    - tests
  imports:
    - uvloop
  requires:
    - pip
    - pytest
    - aiohttp
    - psutil
    - pyopenssl
  commands:
    - pip check
    - pytest -ra -k "not (test_sourcecode)"

about:
  home: https://github.com/MagicStack/uvloop
  license: MIT OR Apache-2.0
  license_family: Other
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
  summary: Ultra fast implementation of asyncio event loop on top of libuv.
  description: |
    uvloop is a fast, drop-in replacement of the built-in asyncio event loop.
    uvloop is implemented in Cython and uses libuv under the hood.
  doc_url: https://uvloop.readthedocs.io/
  dev_url: https://github.com/MagicStack/uvloop

extra:
  recipe-maintainers:
    - nehaljwani
    - carlodri
    - jakirkham
