{% set name = "uvloop" %}
{% set version = "0.22.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c84bae345b9147082b17371e3dd5d42775bddce91f885499017f4607fdaf39f

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --config-settings="--build-option=build_ext" --config-settings="--build-option=--cython-always" --config-settings="--build-option=--use-system-libuv"
  skip: true  # [py<38 or win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=60
    - wheel
    - cython >=3.1,<4
    - libuv {{ libuv }}
  run:
    - python
    - {{ pin_compatible("libuv", max_pin="x") }}
  run_constrained:
    - python >=3.8.1

# The test fails because SSL connection closure completes the data_received future earlier than the test expects.
{% set deselect_tests = " --deselect=tests/test_context.py::Test_UV_Context::test_create_ssl_server_manual_connection_lost" %}
# file .flake8 was removed from the release on pypi and GitHub.
{% set deselect_tests = deselect_tests + " --deselect=tests/test_sourcecode.py::TestSourceCode::test_flake8" %}
# Passed locally but randomly failed on build platform:
# AssertionError: timed out
{% set deselect_tests = deselect_tests + " --deselect=tests/test_tcp.py::Test_AIO_TCP::test_create_connection_open_con_addr" %}
# AssertionError: Didn't reach a full buffer
{% set deselect_tests = deselect_tests + " --deselect=tests/test_pipes.py::Test_UV_Pipes::test_write_buffer_full" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_pipes.py::Test_AIO_Pipes::test_write_buffer_full" %}
# ProcessPoolExecutor fork-safety issues on Python 3.14:
# Three uvloop tests fail on Python 3.14 with `BrokenProcessPool` errors and libuv deadlocks.
{% set deselect_tests = deselect_tests + " --deselect=tests/test_pipes.py::TestUVExecutors::test_executors_process_pool_01" %}   # [linux and py==314]
{% set deselect_tests = deselect_tests + " --deselect=tests/test_pipes.py::TestAIOExecutors::test_executors_process_pool_01" %}  # [linux and py==314]
{% set deselect_tests = deselect_tests + " --deselect=tests/test_pipes.py::TestIssue39Regr::test_issue39_regression" %}          # [linux and py==314]

test:
  source_files:
    - tests
    - pyproject.toml
    - mypy.ini
  imports:
    - uvloop
  commands:
    - pip check
    - pytest -v {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - psutil
    - pyopenssl

about:
  home: https://github.com/MagicStack/uvloop
  license: MIT OR Apache-2.0
  license_family: Other
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
  summary: Ultra fast implementation of asyncio event loop on top of libuv.
  description: |
    uvloop is a fast, drop-in replacement of the built-in asyncio event loop.
    uvloop is implemented in Cython and uses libuv under the hood.
  doc_url: https://uvloop.readthedocs.io
  dev_url: https://github.com/MagicStack/uvloop

extra:
  recipe-maintainers:
    - nehaljwani
    - carlodri
    - jakirkham
