{% set name = "uvloop" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1a503d5b49da6e3dd5607d6e533a5315b1caedbf629901807c65a23a09cad065
  patches:
    - 0001-Prefer-SO_REUSEPORT-over-uv.SO_REUSEPORT.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --global-option='build_ext' --global-option='--cython-always'
  skip: true  # [py2k or win]

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]
  host:
    - python
    - cython >=0.28
    - pip
  run:
    - python

test:
  imports:
    - uvloop

about:
  home: http://github.com/MagicStack/uvloop
  # Multiple licenses! : Apache 2.0, MIT
  license: MIT
  license_file: LICENSE-MIT
  summary: Ultra fast implementation of asyncio event loop on top of libuv.
  description: |
    uvloop is a fast, drop-in replacement of the built-in asyncio event loop.
    uvloop is implemented in Cython and uses libuv under the hood.
  doc_url: http://uvloop.readthedocs.org
  dev_url: https://github.com/MagicStack/uvloop

extra:
  recipe-maintainers:
    - nehaljwani
    - carlodri
