{% set name = "uvloop" %}
{% set version = "0.22.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c84bae345b9147082b17371e3dd5d42775bddce91f885499017f4607fdaf39f

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --config-settings="--build-option=build_ext" --config-settings="--build-option=--cython-always" --config-settings="--build-option=--use-system-libuv"
  skip: true  # [py<381 or win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython >=3.1,<4.dev0
    - pip
    - libuv 1.44.2
    - setuptools >=60
    - wheel
  run:
    - python
    - {{ pin_compatible("libuv", max_pin="x") }}

test:
  source_files:
    - pyproject.toml
    - tests
  imports:
    - uvloop
  requires:
    - pip
    - pytest
    - psutil
    - pyopenssl
  commands:
    - pip check
    - pytest -ra -k "not (test_sourcecode)"  # [not osx]
    # skip test_process_delayed_stdio__not_paused__no_stdin: time is not monotonic on CI
    - pytest -ra -k "not (test_sourcecode or test_process_delayed_stdio__not_paused__no_stdin or test_create_ssl_server_manual_connection_lost or test_fs_event_rename)"  # [osx]

about:
  home: https://github.com/MagicStack/uvloop
  license: MIT OR Apache-2.0
  license_family: Other
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
  summary: Ultra fast implementation of asyncio event loop on top of libuv.
  description: |
    uvloop is a fast, drop-in replacement of the built-in asyncio event loop.
    uvloop is implemented in Cython and uses libuv under the hood.
  doc_url: https://uvloop.readthedocs.io/
  dev_url: https://github.com/MagicStack/uvloop

extra:
  recipe-maintainers:
    - nehaljwani
    - carlodri
    - jakirkham
