travis:
  secure:
    BINSTAR_TOKEN: BBrbO20Bvdv6VDnV7RvfrPL1u6cQKYfYnZq4p5+9b9/OY/9S9GNMx3DdBpkpJtb83wymaPbf4FH8bQCiuDDJTEb3MUJnwsBWrthQ2iIqRIgqLn+kc4Ctx88jB5xLpXFzdbCFBmWcqkr/wN1RgY/XQVBQlLABE38ua7PUyaYaLpVY4vns3sgDOBGAUgQT3VNJBJD8ps6IiXIrDoT8UP3G0fbIhSV64N/jZSm8MAPXD0OhXk0R3AgYeUOOjaJQyrCLmA2BlkZBBgQytRO2o6sqb7F2lyf0fWBsH/Qb0OvQ8D4w/6Y1fBRj9+Hhi67ztRTu4y3gwWRo3qn29IxYyw246oKELhrKHRxu0lnP2EnM99pAJG4cxHpEYYHOoNLNJSaLpbGaBqlVExnt2tguMRrQvi3Jdbq8+Jfc9RxhV+nNG699ofJwPJhBHrpp7ODtom7GmhmaSXwbyHFtLZM3MMQno8CiqOt+gPYP4Jya5FiNjwKrS+zprKd+W8XKO6LF3MN/PZHumhrDxX3W3c0DFYn9UBD2v7nRTCmzTMxE8iKeThzbzpC2QTjEVQ930uo1wlo6nvZBCd+Q9+wTicJMvTEtz6X1ry19PgD6Td3M31YQkLLx3AYND+4uV7+XrQwUBkKeoByqbbe9mty2iysYNZYFPa0Ko/p32Bnow3hGSCsEc04=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
